Repository rhinstaller/dasbus, pull requests merged in 2020-04, with the labels that each got.

#24 Remove generate_dictionary_from_data
  dasbus/structure.py
  tests/test_structure.py
Labels: bug, incompatible change, master

#21 Generate the documentation
  docs/Makefile
  docs/api/dasbus.client.rst
  docs/api/dasbus.rst
  docs/api/dasbus.server.rst
  docs/api/modules.rst
  docs/conf.py
  docs/index.rst
  docs/make.bat
Labels: documentation, master

#25 Replace the error register with the error mapper
  README.md
  dasbus/client/handler.py
  dasbus/client/proxy.py
  dasbus/connection.py
  dasbus/error.py
  dasbus/server/handler.py
  examples/04_register/common.py
  tests/test_client.py
  tests/test_connection.py
  tests/test_dbus.py
  tests/test_error.py
  tests/test_server.py
Labels: bug, incompatible change, master

#27 Enable Codecov
  .travis.yml
  README.md
Labels: master

#26 Update the documentation
  .readthedocs.yml
  .travis.yml
  .travis/Dockerfile.fedora-rawhide
  Makefile
  dasbus/client/observer.py
  dasbus/loop.py
  dasbus/server/container.py
  dasbus/server/interface.py
  dasbus/server/property.py
  dasbus/server/publishable.py
  dasbus/server/template.py
  dasbus/typing.py
  docs/Makefile
  docs/api/dasbus.client.handler.rst
  docs/api/dasbus.client.observer.rst
  docs/api/dasbus.client.property.rst
  docs/api/dasbus.client.proxy.rst
  docs/api/dasbus.client.rst
  docs/api/dasbus.connection.rst
  docs/api/dasbus.constants.rst
  docs/api/dasbus.error.rst
  docs/api/dasbus.identifier.rst
  docs/api/dasbus.loop.rst
  docs/api/dasbus.namespace.rst
  docs/api/dasbus.rst
  docs/api/dasbus.server.container.rst
  docs/api/dasbus.server.handler.rst
  docs/api/dasbus.server.interface.rst
  docs/api/dasbus.server.property.rst
  docs/api/dasbus.server.publishable.rst
  docs/api/dasbus.server.rst
  docs/api/dasbus.server.template.rst
  docs/api/dasbus.signal.rst
  docs/api/dasbus.specification.rst
  docs/api/dasbus.structure.rst
  docs/api/dasbus.typing.rst
  docs/api/dasbus.xml.rst
  docs/api/modules.rst
  docs/conf.py
  docs/environment.yml
  docs/examples.rst
  docs/index.rst
Labels: documentation, master

#28 Fix minor typos
  dasbus/client/observer.py
  dasbus/client/proxy.py
  dasbus/error.py
  dasbus/server/container.py
  dasbus/server/interface.py
  tests/test_server.py
Labels: documentation, master

#29 Fix the documentation
  README.md
  dasbus/client/observer.py
  dasbus/error.py
  docs/api/dasbus.rst
  docs/examples.rst
  docs/index.rst
  examples/02_notification/client.py
Labels: documentation, master
