Repository rhinstaller/dasbus, pull requests merged in 2020-06, with the labels that each got.

#36 Improve the support for interface proxies
  dasbus/connection.py
  dasbus/identifier.py
  tests/test_client.py
  tests/test_connection.py
  tests/test_dbus.py
  tests/test_identifier.py
Labels: enhancement, master

#35 Make the message bus of a service identifier accessible
  dasbus/identifier.py
  tests/test_identifier.py
Labels: enhancement, master

#33 Document differences between dasbus and pydbus
  docs/index.rst
  docs/pydbus.rst
Labels: documentation, master

#37 Add possibility to change setup.py arguments
  Makefile
Labels: enhancement, master

#38 Improve packit configuration
  .packit.yaml
Labels: master
