Repository rhinstaller/dasbus, pull requests merged in 2022-06, with the labels that each got.

#84 Run tests for Debian and Ubuntu in Travis
  .travis.yml
  .travis/Dockerfile.debian-latest
  .travis/Dockerfile.ubuntu-devel
  README.md
Labels: documentation, ci and tests

#91 Fix pylint issues
  .pylintrc
  .travis/Dockerfile.centos-stream-8
  .travis/Dockerfile.centos-stream-9
  .travis/Dockerfile.debian-latest
  .travis/Dockerfile.fedora-rawhide
  .travis/Dockerfile.ubuntu-devel
  Makefile
  dasbus/client/property.py
  dasbus/typing.py
Labels: ci and tests

#78 Support unixfd transfer via dbus
  dasbus/client/handler.py
  dasbus/connection.py
  dasbus/server/handler.py
  docs/pydbus.rst
  tests/test_client.py
  tests/test_dbus.py
Labels: enhancement

#92 Raise TimeoutError if a DBus call times out
  dasbus/client/handler.py
  docs/examples.rst
  tests/test_client.py
  tests/test_dbus.py
Labels: enhancement

#94 UnixFD: Rename a parameter to server_arguments
  dasbus/connection.py
Labels: refactoring

#93 UnixFD: Revert a change in GLibClient._async_call_finish
  dasbus/client/handler.py
  tests/test_client.py
Labels: refactoring
